version: '3.8'

services:
  milvus:
    image: milvusdb/milvus:latest
    command: ["standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus_data:/var/lib/milvus
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${KBS_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${KBS_DB_PASSWORD:-postgres}
      - POSTGRES_DB=${KBS_DB_NAME:-kbs}

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${KBS_DB_PASSWORD:-root}
      - MYSQL_DATABASE=${KBS_DB_NAME:-kbs}
      - MYSQL_USER=${KBS_DB_USER:-kbs}
      - MYSQL_PASSWORD=${KBS_DB_PASSWORD:-kbs}

volumes:
  milvus_data:
  postgres_data:
  mysql_data: 